# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_labels_and_preds": "00_core.ipynb",
         "visualize_cam_on_img": "00_core.ipynb",
         "rename_in_order": "00_core.ipynb",
         "init_images_dir": "00_core.ipynb",
         "split_images_into_train_valid_test": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://wshuyi.github.io/image_classification_helper/"

git_url = "https://github.com/wshuyi/image_classification_helper/tree/master/"

def custom_doc_links(name): return None
