package:
  name: image_classification_helper
  version: 0.0.3
source:
  sha256: 9be3793b6a35f71f624d981d523d18a2ee46b80d83055a7085d5831d479f90df
  url: https://files.pythonhosted.org/packages/90/23/bb209904af70cb7110e2d63b93ede287361a09a7c1739fb6c35e6b51b7a6/image_classification_helper-0.0.3.tar.gz
about:
  dev_url: https://wshuyi.github.io
  doc_url: https://wshuyi.github.io
  home: https://wshuyi.github.io
  license: Apache Software
  license_family: APACHE
  summary: Image Classification Helper for class demo
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - wshuyi
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - image_classification_helper
